<?php
// $Id: xoops_version.php,v 1.3 2006/03/06 00:26:33 skenow Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

$modversion['name'] = 'PHPGedView';
$modversion['version'] = 1.01;
$modversion['description'] = 'PhpGedView is a revolutionary genealogy program which allows you to view and edit your genealogy on your website.';
$modversion['credits'] = 'John Finlay & Others (http://www.PhpGedView.net/)';
$modversion['author'] = 'Steve Kenow, Patrick Kellum';
$modversion['help'] = '';
$modversion['license'] = 'GNU General Public License (GPL) see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'pgv_slogo.png';
$modversion['dirname'] = 'pgv';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'pgv_blocks';
$modversion['tables'][1] = 'pgv_dates';
$modversion['tables'][2] = 'pgv_families';
$modversion['tables'][3] = 'pgv_favorites';
$modversion['tables'][4] = 'pgv_individuals';
$modversion['tables'][5] = 'pgv_messages';
$modversion['tables'][6] = 'pgv_names';
$modversion['tables'][7] = 'pgv_news';
$modversion['tables'][8] = 'pgv_other';
$modversion['tables'][9] = 'pgv_placelinks';
$modversion['tables'][10] = 'pgv_places';
$modversion['tables'][11] = 'pgv_sources';
$modversion['tables'][12] = 'pgv_users';
$modversion['tables'][13] = 'pgv_media';
$modversion['tables'][14] = 'pgv_media_mapping';
$modversion['tables'][15] = 'pgv_tblver';

// Install/Uninstall/Update
$modversion['onInstall'] = 'xoops_install_funcs.php';
$modversion['onUninstall'] = 'xoops_install_funcs.php';
$modversion['onUpdate'] = 'xoops_install_funcs.php';

//Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin.php';
$modversion['adminmenu'] = 'xoops_adminmenu.php';

// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = 'Welcome Page';
$modversion['sub'][1]['url'] = 'index.php?command=gedcom';
$modversion['sub'][2]['name'] = 'MyGedView Portal';
$modversion['sub'][2]['url'] = 'index.php?command=user';

// Search
//$modversion['hasSearch'] = 1;
//$modversion['search']['file'] = 'xoops_search.php';
//$modversion['search']['func'] = 'pgv_search';

// Smarty
$modversion['use_smarty'] = 1;
?>