<?php
# $Id: help_text.fr.php,v 1.1 2005/10/07 18:08:36 skenow Exp $
if (preg_match("/help_text\...\.php$/", $_SERVER["PHP_SELF"])>0) {
  print "You cannot access a language file directly.";
  exit;
}

$pgv_lang["remember_me_help"]           = "~Resté mémorisé~<br /><br />En cochant cette case, vos paramètres seront mémorisés, évitant d'avoir à vous connecter la prochaine fois où vous reviendrez sur ce site.<br /><br />Cependant, pour des raisons de sécurité, vous devrez vous identifier de nouveau pour avoir accès aux fonctions d'administration.<br /><br />Les informations sont enregistrées dans un <i>cookie</i>.<br /><br />NE PAS UTILISER cette option sur un ordinateur public, cela permettrait à n'importe qui de consulter les données protégées.";
$pgv_lang["edit_NCHI_help"]             = "~#factarray[NCHI]# HELP~<br /><br />Entrer le nombre d'enfants pour cet individu ou cette famille. Ce champ est facultatif.<br /><br />";
$pgv_lang["edit_TIME_help"]             = "~#factarray[TIME]# HELP~<br /><br />Entrer l'heure de l'évènement sous la forme HH:MM. Exemples: 04:50 13:00 20:30.<br /><br />";
$pgv_lang["edit_NOTE_help"]             = "~#factarray[NOTE]# HELP~<br /><br />Une note est un texte libre qui s'affichera dans l'onglet Détails.<br /><br />";
$pgv_lang["edit_CEME_help"]             = "~#factarray[CEME]# HELP~<br /><br />Entrer le nom du cimetière où cette personne est enterrée. Exemple : Père-Lachaise.<br />La commune est à saisir dans le champ lieu.<br /><br />";
$pgv_lang["edit_ASSO_help"]             = "~#factarray[ASSO]# HELP~<br /><br />Entrer l'identifiant GEDCOM de la personne à associer.<br /><br />";
$pgv_lang["edit_RELA_help"]             = "~#factarray[RELA]# HELP~<br /><br />Choisir dans la liste le lien entre les deux personnes.<br />Exemple : en choisissant 'Parrain', cela signifie que la personne associée est le parrain de l'individu sélectionné.<br /><br />";
$pgv_lang["edit_SPFX_help"]             = "~#factarray[SPFX]# HELP~<br /><br />Entrer les(s) préfixe(s) pour le nom de famille.<br />Exemple : 'de la' pour Louis de la Martinière.<br /><br />Si la première lettre du préfixe est une majuscule, le nom sera trié sur ce préfixe :<br />'De la Martinière' sera classé à la lettre 'D'.<br />Inversement, pour une minuscule le tri se fera sur la première lettre du nom :<br />'de la Martinière' sera classé à la lettre 'M'.";

//-- GENERAL
$pgv_lang["help_header"]                = "<span class=\"error\"><small>Avertissement : certains textes d'aide n'ont pas encore été traduits en français.</small></span><br/><br/>Aide sur : ";
$pgv_lang["privacy_error_help"]         = "<b>Détails privés</b><br /><br />Plusieurs raisons possibles à ce message :<dl><dt>1. Vous n'êtes pas inscrit sur ce site</dt><dd>Les détails sur les personnes vivantes sont masqués.<br />Les visiteurs non authentifiés ont accès aux fiches des personnes décédées uniquement.<br />Vous pouvez faire une demande de compte.</dd><dt>2. Vous disposez d'un compte et d'un mot de passe</dt><dd>mais vous avez oublié de vous connecter.</dd><dt>3. Information marque 'Privé'</dt><dd>La personne sélectionnée a demandé ce verrouillage à l'administrateur<br />Dans ce cas, seul l'administrateur a l'accès aux détails sur cette personne.</dd><dt>4. Vous n'avez pas de lien direct</dt><dd>Même pour les utilisateurs déclarés et connectés, certaines informations ne sont accessibles qu'aux proches, suivant le degré fixé par l'administrateur.<br />Exemples:<br />Pour le degré <b>1</b>, vous verrez les détails de votre propre famille, père, mère, frère, sœur (mais pas leurs conjoints ni vos neveux et nièces)<br />Pour le degré <b>2</b>, vous verrez en plus les conjoints de vos frères/sœurs et vos neveux/nièces.<br />Plus le degré est élevé, plus vous voyez de proches.<br />Si vous pouvez justifier d'un lien de parenté, contacter l'administrateur.</dd></dl>";
$pgv_lang["more_help"]                  = "<br />Pour une aide plus détaillée, vérifier l'option <b>#pgv_lang[show_context_help]#</b> dans le menu <b>#pgv_lang[page_help]#</b>, et suivre les liens <b>#pgv_lang[qm]#</b> de la page.<br />";
$pgv_lang["more_config_help"]           = "<br /><b>Aide détaillée</b><br />Une aide plus détaillée est disponible.<br />Suivre les liens <b>?</b> de la page.<br /><br />";
$pgv_lang["start_admin_help"]           = "+++ Début du complément d'informations de l'administrateur +++";
$pgv_lang["end_admin_help"]             = "--- Fin du complément d'informations de l'administrateur ---";
$pgv_lang["multiple_help"]              = "<center>--- Aide commune à plusieurs pages ---</center>";
$pgv_lang["header_general_help"]        = "<div class=\"name_head\"><center><b>Informations générales</b></center></div><br />";
$pgv_lang["best_display_help"]          = "~#pgv_lang[resolution]#~<br />PhpGedView est prévu pour une taille d'écran de 1024x768 pixels.<br />Il s'agit de la valeur minimum pour que tout s'affiche correctement.<br />Avec une résolution inférieure, par exemple 800x600, vous devrez souvent utiliser les ascenceurs (scrolling).<br />";
$pgv_lang["preview_help"]               = "~#pgv_lang[print]#~<br />Le lien <b>#pgv_lang[print_preview]#</b> en bas de chaque page permet une impression plus propre en n'affichant pas les menus, les liens, les boutons d'aide...<br /><br />Le lien <b>#pgv_lang[print_preview]#</b> devient alors <b>#pgv_lang[print]#</b>, et affiche votre menu d'impression habituel.<br />Après l'impression, utilisez simplement le bouton <b>Retour</b> de votre navigateur.<br /><br /><b>Note :</b><br />En mode <b>#pgv_lang[print_preview]#</b> la plupart des liens sont cachés. Les liens sur les boîtes et les personnes restent néanmoins actifs.<br />";
$pgv_lang["readme_help"]                = "<center>Voir le fichier <a href=\"readme.txt\" target=\"_blank\"><b>Readme.txt</b></a> pour davantage d'informations.</center>";
$pgv_lang["is_user_help"]               = "--- Texte identique à l'aide visiteur. --- <br />--- Pour économiser de la place, il n'y a pas de texte spécial administrateur ici. ---";
$pgv_lang["edit_raw_gedcom_help"]       = "~#pgv_lang[edit_raw]#~<br /><br />En cliquant sur ce lien, une nouvelle fenêtre s'ouvre permettant la <B>modification</B> de l'enregistrement GEDCOM.<br />Respecter impérativement la syntaxe GEDCOM 5.5 car aucun contrôle n'est réalisé.<br />Les modifications effectuées seront soumises à l'approbation de l'administrateur.";
$pgv_lang["RESN_help"]                  = "~Restrictions d'accès sur un enregistrement~<br /><br />En plus des règles globales de restrictions d'accès, PhpGedView offre la possibilité d'ajouter des restrictions d'accès en lecture et/ou écriture à certains enregistrements concernant une Famille ou un Individu.<br /><br />Valeurs possibles pour ce champ :<br /><ul><li><b>#pgv_lang[none]#</b><br/>Les administrateurs du site ou du fichier GEDCOM, ainsi que les utilisateurs avec privilèges, peuvent modifier l'information. Pour les autres, la lecture est autorisée conformément aux règles de restrictions globales.</li><li><b>#pgv_lang[locked]#</b><br />Le droit de modification est réservé aux administrateurs, et à l'utilisateur dont ce sont les propres informations.</li><li><b>#pgv_lang[privacy]#</b><br />L'information est cachée, sauf aux administrateurs et à l'utilisateur concerné.</li><li><b>#pgv_lang[confidential]#</b><br />Information accessible aux seuls administrateurs.</li></ul><br /><table><tr><th></th><th colspan=2>Admin</th><th colspan=2>Individu</th><th colspan=2>Autres</th></tr><tr><th></th><th>R</th><th>W</th><th>R</th><th>W</th><th>R</th><th>W</th></tr><tr><td><img src=\"images/RESN_none.gif\" alt=\"\"/> #pgv_lang[none]#</td><th><img src=\"images/checked.gif\"/></th><th><img src=\"images/checked.gif\"/></th><th><img src=\"images/checked_qm.gif\"/></th><th><img src=\"images/checked_qm.gif\"/></th><th><img src=\"images/checked_qm.gif\"/></th><th><img src=\"images/checked_qm.gif\"/></th></tr><tr><td><img src=\"images/RESN_locked.gif\" alt=\"\"/> #pgv_lang[locked]#</td><th><img src=\"images/checked.gif\"/></th><th><img src=\"images/checked.gif\"/></th><th><img src=\"images/checked_qm.gif\"/></th><th><img src=\"images/checked_qm.gif\"/></th><th><img src=\"images/checked_qm.gif\"/></th><th><img src=\"images/forbidden.gif\"/></th></tr><tr><td><img src=\"images/RESN_privacy.gif\" alt=\"\"/> #pgv_lang[privacy]#</td><th><img src=\"images/checked.gif\"/></th><th><img src=\"images/checked.gif\"/></th><th><img src=\"images/checked_qm.gif\" /></th><th><img src=\"images/checked_qm.gif\"/></th><th><img src=\"images/forbidden.gif\"/></th><th><img src=\"images/forbidden.gif\"/></th></tr><tr><td><img src=\"images/RESN_confidential.gif\" alt=\"\"/> #pgv_lang[confidential]#</td><th><img src=\"images/checked.gif\"/></th><th><img src=\"images/checked.gif\"/></th><th><img src=\"images/forbidden.gif\"/></th><th><img src=\"images/forbidden.gif\"/></th><th><img src=\"images/forbidden.gif\"/></th><th><img src=\"images/forbidden.gif\"/></th></tr></table><ul><li>R : droit de lire</li><li>W : droit de modifier</li><li><img src=\"images/checked_qm.gif\"/> : droits selon les règles de restrictions globales</li></ul>";

//-- Pages Help-messages
//-- Index-page
$pgv_lang["index_help"]                 = "~#pgv_lang[welcome_page]#~<br />Bienvenue sur la page d'accueil du fichier <a href=\"#def_gedcom\">GEDCOM</a> sélectionné. A tout moment vous pouvez revenir sur cette page par le bouton <b>#pgv_lang[welcome_page]#</b> du menu principal. Si plusieurs fichiers GEDCOM sont disponibles, faîtes-votre choix dans le menu déroulant<br /><br /><b>Ici vous trouverez de l'aide sur:</b><br /><li><a href=\"#header_general\">Informations générales</a><li><a href=\"#header\">#pgv_lang[header]#</a><li><a href=\"#menu\">Menus</a><li><a href=\"#index_portal\">#pgv_lang[welcome_page]#</a><li><a href=\"#def\">Définitions</a><br /><br />La version #VERSION# de <a href=\"#def_pgv\">PhpGedView</a> apporte des améliorations sur la présentation, les menus, la page d'accueil, et de nombreuses fonctions ont été revues.<br /><br />";

//-- Index-page Header
$pgv_lang["header_help"]                = "<div class=\"name_head\"><center><b>#pgv_lang[header]#</b></center></div><br />En haut de chaque page s'affichent des boutons et liens utilisables à tout moment.<br />La présentation du site étant personnalisable, le bandeau est variable selon le <a href=\"#def_theme\">thème</a> choisi.<br /><br /><b>Voici la liste des liens que vous pourrez y trouver :</b><li><a href=\"#header_search\">#pgv_lang[search]#</a><li><a href=\"#header_lang_select\">#pgv_lang[change_lang]#</a><li><a href=\"#header_user_links\">#pgv_lang[login]#</a><li><a href=\"#header_favorites\">#pgv_lang[gedcom_favorites]#</a><li><a href=\"#header_theme\">#pgv_lang[change_theme]#</a><br />";
$pgv_lang["header_search_help"]         = "~#pgv_lang[header]# «#pgv_lang[search]#»~<br />Cette boîte de recherche est petite mais puissante.<br />Laissez PhpGedView chercher pour vous.<br />Vous trouverez une aide détaillée sur la page de recherche.<br />";
$pgv_lang["header_lang_select_help"]    = "~#pgv_lang[header]# «#pgv_lang[change_lang]#»~<br />PhpGedView est multi-langues. Par défaut il démarre dans la langue de votre navigateur.<br />Vous pouvez changer de langue en utilisant le <B>menu déroulant</B> ou bien la liste des <B>drapeaux</B> en couleur.<br />";
$pgv_lang["header_user_links_help"]     = "~#pgv_lang[header]# «#pgv_lang[login]#»~<br />Cette liste de liens reste présente au même endroit sur toutes les pages (sauf si vous changez le thème).<br />Non connecté, vous voyez uniquement le lien <B>#pgv_lang[login]#</B>.<br />Connecté, vous voyez <b>#pgv_lang[logged_in_as]#</b>. Ce lien vous donne l'accès à votre compte. Cliquer sur <B>#pgv_lang[logout]#</B> pour vous déconnecter.<br />Si vous avez les droits d'administrateur, le lien <B>#pgv_lang[admin]#</B> s'affiche.<br />";
$pgv_lang["header_favorites_help"]      = "~#pgv_lang[header]# «#pgv_lang[gedcom_favorites]#»~<br />Cette liste affiche les liens favoris que vous avez sélectionnés. S'y ajoutent les favoris enregistrés pour ce fichier GEDCOM par l'administrateur.<br />Ces liens vous offrent l'accès direct à la page détaillée de l'individu choisi.<br />Pour savoir comment ajouter un favori, consulter l'aide sur la page <B>#pgv_lang[my_favorites]#</B>.<br />";
$pgv_lang["header_theme_help"]          = "~#pgv_lang[header]# «#pgv_lang[change_theme]#»~<br />Si l'administrateur l'autorise, vous pouvez choisir votre thème dans une liste, et modifier ainsi l'affichage du site. Si vous êtes connecté, ce thème sera mémorisé et deviendra votre thème par défaut.<br />";

//-- Index-page Menu
$pgv_lang["menu_help"]                  = "<div class=\"name_head\"><center><b>Menus</b></center></div><br />En passant votre souris sur l'icone d'un menu, un sous-menu s'affiche.<br />Un clic vous emmène sur la page du premier sous-menu.<br /><br />Liste des menus disponibles:</b><br /><li><a href=\"#menu_fam\">#pgv_lang[welcome_page]#</a><br /><li><a href=\"#menu_myged\">#pgv_lang[mygedview]#</a><br /><li><a href=\"#menu_charts\">#pgv_lang[charts]#</a><br /><li><a href=\"#menu_lists\">#pgv_lang[lists]#</a><br /><li><a href=\"#menu_annical\">#pgv_lang[anniversary_calendar]#</a><br /><li><a href=\"#menu_clip\">#pgv_lang[clippings_cart]#</a><br /><li><a href=\"#menu_search\">#pgv_lang[search]#</a><br /><li><a href=\"#menu_rslog\">#pgv_lang[research_log]#</a><br /><li><a href=\"#menu_help\">#pgv_lang[page_help]#</a><br /><br />";
$pgv_lang["menu_famtree_help"]          = "~#pgv_lang[menu]# «#pgv_lang[welcome_page]#»~<br />Tous les fichiers GEDCOM disponibles sur le site sont présentés ici. Chacun ayant sa propre présentation.<br />Quand le site ne présente qu'un seul fichier GEDCOM, ce sous-menu est vide.<br /><br />";
$pgv_lang["menu_myged_help"]            = "~#pgv_lang[menu]# «#pgv_lang[mygedview]#»~<br />Si vous êtes connecté, ce menu présente les choix suivants :<dl><dt>#pgv_lang[mygedview]#</dt><dd>Vous renvoie sur votre propre #pgv_lang[welcome_page]#.</dd><dt>#pgv_lang[editowndata]#</dt><dd>Pour modifier vos paramètres personnels.</dd><dt>#pgv_lang[my_pedigree]#</dt><dd>Si vous avez choisi un #pgv_lang[root_person]# pour ce fichier GEDCOM, son #pgv_lang[index_header]# s'affichera</dd><dt>#pgv_lang[my_indi]#</dt><dd>Lien vers votre page individuelle, où se trouvent les données de votre propre famille.</dd></dl>";
$pgv_lang["menu_charts_help"]           = "~#pgv_lang[menu]# «#pgv_lang[charts]#»~<br />Liste des diagrammes disponibles :<dl><dt><a href=\"?help=help_pedigree.php\">#pgv_lang[index_header]#</a></dt><dd>Affiche les parents de l'individu racine du fichier GEDCOM. Vous pouvez le modifier si vous êtes connecté.</dd><dt><a href=\"?help=help_descendancy.php\">#pgv_lang[descend_chart]#</a></dt><dd>Même principe. Affiche la liste des enfants.</dd><dt><a href=\"?help=help_timeline.php\">#pgv_lang[timeline_chart]#</a></dt><dd>Affiche les évènements d'une ou plusieurs personnes sur une même ligne de temps, permettant de les comparer.</dd><dt><a href=\"?help=help_relationship.php\">#pgv_lang[relationship_chart]#</a></dt><dd>Recherche du lien de parenté entre deux personnes</dd><dt><a href=\"?help=help_ancestry.php\">#pgv_lang[ancestry_chart]#</a></dt><dd>Présentation sous forme #pgv_lang[ancestry_list]# ou #pgv_lang[ancestry_booklet]#</dd><dt><a href=\"?help=help_fanchart.php\">#pgv_lang[fan_chart]#</a></dt><dd>Présentation en roue ou en éventail.</dd></dl>";
$pgv_lang["menu_lists_help"]            = "~#pgv_lang[menu]# «#pgv_lang[lists]#»~<br />Les choix suivants sont présentés dans ce menu:<dl><dt><a href=\"?help=help_indilist.php\">#pgv_lang[individual_list]#</a></dt><dd>Présentation alphabétique des individus du fichier GEDCOM.</dd><dt><a href=\"?help=help_famlist.php\">#pgv_lang[family_list]#</a></dt><dd>Présentation alphabétique des familles du fichier GEDCOM.</dd><dt><a href=\"?help=help_sourcelist.php\">#pgv_lang[source_list]#</a></dt><dd>Liste des sources d'informations citées dans ce fichier GEDCOM.</dd><dt><a href=\"?help=help_placelist.php\">#pgv_lang[place_list]#</a></dt><dd>Liste par lieux sur deux colonnes : à gauche les individus et à droite les familles.</dd><dt><a href=\"?help=help_medialist.php\">#pgv_lang[media_list]#</a></dt><dd>Cette option ne s'affiche que si l'administrateur l'a autorisé.<br />Liens vers tous les OBJEts MultiMedia de ce fichier GEDCOM.</dd></dl>";
$pgv_lang["menu_annical_help"]          = "~#pgv_lang[menu]# «#pgv_lang[anniversary_calendar]#»~<br />Affiche les évènements ayant eu lieu à une certaine date. Choix entre une présentation par jour (ex: <tt>5 Avril</tt>), par mois (ex: <tt>Avril</tt>>) ou par année (ex: <tt>1999</tt>>).<dl><dt>#pgv_lang[viewday]#</dt><dd>Affichage du calendrier #pgv_lang[on_this_day]#.</dd><dt>#pgv_lang[viewmonth]#</dt><dd>Affichage du calendrier #pgv_lang[in_this_month]#.</dd><dt>#pgv_lang[viewyear]#</dt><dd>Affichage du calendrier #pgv_lang[in_this_year]#.</dd></dl>";
$pgv_lang["menu_clip_help"]             = "~#pgv_lang[menu]# «#pgv_lang[clippings_cart]#»~<br />Si l'administrateur l'a autorisé, ce menu s'affiche sur le bandeau.<br />Un panier vous permet de collecter des informations.<br /><br />";
$pgv_lang["menu_search_help"]           = "~#pgv_lang[menu]# «#pgv_lang[search]#»~<br />Accès à une page de recherche très puissante.<br /><br />";
$pgv_lang["menu_help_help"]             = "~#pgv_lang[menu]# «#pgv_lang[page_help]#»~<br />#pgv_lang[help_help_items]#";

//-- Index-page Portal
$pgv_lang["index_portal_head_help"]     = "<div class=\"name_head\"><center><b>#pgv_lang[welcome_page]#</b></center></div><br />";
$pgv_lang["index_portal_help"]          = "La #pgv_lang[welcome_page]# présente plusieurs blocs séparés, et elle est personnalisable. Ainsi, chaque fichier GEDCOM de ce site peut avoir sa propre #pgv_lang[welcome_page]#.<br /><br />Voici la liste des blocs disponibles :<ul><li><a href=\"#index_welcome\">#pgv_lang[welcome_block]#</a><li><a href=\"#index_login\">#pgv_lang[login_block]#</a><li><a href=\"#index_events\">#pgv_lang[upcoming_events_block]#</a><li><a href=\"#index_onthisday\">#pgv_lang[todays_events_block]#</a><li><a href=\"#index_favorites\">#pgv_lang[gedcom_favorites_block]#</a><li><a href=\"#index_stats\">#pgv_lang[gedcom_stats_block]#</a><li><a href=\"#index_media\">#pgv_lang[random_media_block]#</a><li><a href=\"#index_loggedin\">#pgv_lang[logged_in_users_block]#</a><li><a href=\"#gedcom_news\">#pgv_lang[gedcom_news_block]#</a><li><a href=\"#recent_changes\">#pgv_lang[recent_changes_block]#</a></ul>";
$pgv_lang["index_welcome_help"]         = "~#pgv_lang[welcome_block]#~<br />Ce bloc affiche :<br />Le fichier GEDCOM actif, et suivant la configuration : la date, l'heure et le compteur de visites.<br />Le compteur ne fonctionne que sur les pages #pgv_lang[welcome_page]# et 'Individu'. Il enregistre le nombre d'accès (<i>hits</i>) à ces pages.<br />Le compteur ne vérifiée pas la provenance des visites, donc quand un même visiteur revisite une page aprèsThe counter does not check the URL of a visitor, so when somebody revisits a page after some time, it will be counted as another Hit.<br />";
$pgv_lang["index_login_help"]           = "~#pgv_lang[login_block]#~<br />Vous n'aurez accès aux informations protégées qu'une fois connecté.<br />Pour cela, entrez votre <b>nom d'utilisateur</b> et votre <b>mot de passe</b>.<br /><br />#pgv_lang[new_password_help]#<br /><br />";
$pgv_lang["index_events_help"]          = "~#pgv_lang[upcoming_events_block]#~<br />This block show you anniversaries of events from the GEDCOM that are coming up in the next month.<br />";
$pgv_lang["index_onthisday_help"]       = "~#pgv_lang[todays_events_block]#~<br />This block works like the \"Upcoming Events\" block, only it displays today's events from your GEDCOM<br />";
$pgv_lang["index_favorites_help"]       = "~#pgv_lang[gedcom_favorites_block]#~<br />Fonctionnement identique au bloc \"My Favorites\", mais il n'est modifiable que par l'administrateur.<br />Son but est d'attirer l'attention des visiteurs sur une personne qui présente un intérêt particulier.<br />La liste déroulante des favoris est disponible à tout moment sur chaque page.<br />Le lien vous conduira vers la page détaillée de l'individu choisi.<br /><br />To save space, the boxes are displayed with limited information. At the right side of the name box you see the magnifying glass to reveal some more information.<br />Clicking the name will forward you to the individual page of the person.<br />Also at the right side you will find a menu, that can take to pages with more information or charts.<br />";
$pgv_lang["index_stats_help"]           = "~#pgv_lang[gedcom_stats_block]#~<br />Ce bloc présente quelques chiffres concernant ce fichier GEDCOM.<br />Si vous souhaitez d'autres informations, utilisez le lien <B>Contact</B> en bas de page.<br /><br />#pgv_lang[index_common_names_help]#";
$pgv_lang["index_common_names_help"]    = "~#pgv_lang[common_surnames]#~<br />Ce bloc affiche la liste des noms de familles les plus fréquents. Leur nombre est déterminé par l'administrateur.<br /><br />En cliquant sur un nom de la liste, vous afficherez la page <b>#pgv_lang[individual_list]#</b>, qui vous donnera davantage de détails.<br />";
$pgv_lang["index_media_help"]           = "~#pgv_lang[random_media_block]#~<br />Ce bloc affiche de façon aléatoire un OBJEt MultiMedia de la base GEDCOM.<br />En cliquant sur l'objet, il s'affichera en taille réelle.<br /><br />Au-dessous de l'objet, vous trouverez un lien vers la fiche de la personne associée à cet objet.<br />";
$pgv_lang["index_loggedin_help"]        = "~#pgv_lang[logged_in_users_block]#~<br />Ce bloc affiche le nombre d'utilisateurs actuellement connectés.";
$pgv_lang["index_gedcom_news_help"]     = "~#pgv_lang[gedcom_news_block]#~<br />The news block is like a bulletin board for this GEDCOM.<br />The site administrator can place important announcements or interesting news messages here.<br /><br />If you have something interesting to display, please contact the site administrator and he can put your message on the bulletin board.";
$pgv_lang["index_gedcom_news_adm_help"] = "#pgv_lang[gedcom_news_block]# accepte les marqueurs <b>HTML</b>.<br />Assurez-vous de bien refermer chaque balise.<br />Une bonne connaissance du langage HTML est recommandée.<br /><br />Ce programme utilise également les <b>feuilles de style (CSS)</b>. Il en existe une pour chaque thème, vous pouvez les utiliser.<br /><br />Le site PhpGedView comporte des exemples sur ce sujet, étudiez-les.<br />";
$pgv_lang["recent_changes_help"]        = "~#pgv_lang[recent_changes_block]#~<br />Ce bloc affiche les modifications les plus récentes suivant les marqueurs CHAN du fichier GEDCOM.";

//-- Index-Page Help
$pgv_lang["help_help"]                  = "La plupart des fonctions peuvent s'utiliser sans explication.<br />Cependant, certains de nos visiteurs ne sont pas très familiers avec l'ordinateur et Internet. Nous leur offrons de l'aide à plusieurs endroits.<br />Dans le menu Aide, vous trouverez les chapitres suivants :<br />";
$pgv_lang["help_page_help"]             = "<dl><dt><b>#pgv_lang[help_for_this_page]#</b></dt><dd>Il existe un texte d'aide pour chaque page. En cliquant sur <b>#pgv_lang[page_help]#</b>, vous aurez une aide générale sur la page active.<br />Pour une aide plus détaillée, ou de l'aide  sur un champ, cliquer sur <B>#pgv_lang[qm]#</B> qui affichera l'aide contextuelle.</dd></dl>";
$pgv_lang["help_content_help"]          = "<dl><dt><b>Sommaire de l'aide</b></dt><dd>Ce menu affiche la liste de tous les textes d'aide disponibles.</dd></dl>";
$pgv_lang["help_qm_help"]               = "<dl><dt><b>#pgv_lang[show_context_help]#</b></dt><dd>L'aide contextuelle est la façon la plus confortable d'obtenir de l'aide.<br />Il suffit de cliquer sur le lien <B>#pgv_lang[qm]#</B> présent en de nombreux endroits.<br />Cette option est débrayable en choisissant <B>#pgv_lang[hide_context_help]#</B>.</dd></dl>";

//-- Index-page Definitions
$pgv_lang["def_help"]                   = "<div class=\"name_head\"><center><b>Définitions</b></center></div><br />Some definitions of words, used in this help text:<br />";
$pgv_lang["def_portal_help"]            = "~Portail~<br />Also on this web site a Portal is like a lobby of a restaurant. It is the place where you enter, but you can also find important information like explanations, menus etc..<br />";
$pgv_lang["def_gedcom_help"]            = "~Fichier GEDCOM~<br />The GEDCOM file is the file that contains all the information about the family.<br />All facts, dates, events, etc. are stored in the GEDCOM file.<br />A GEDCOM file has to follow strict rules, because it is exchangeable between many programs, independent of platforms and/or systems.<br />";
$pgv_lang["def_gedcom_date_help"]       = "~Dates GEDCOM~<br />Since the formats in the GEDCOM files have to follow the International rules, there is an agreement about the notation of the dates as well.<br /><br />Although the date field in a GEDCOM file is a free field (meaning you can even type in just text), here some explanation about typing in correct dates:<br />The full date is entered like DD MMM YYYY like:<br />01 Mar 1801 or 14 Dec 1950<br />If you are missing a part of the date, you can omit that part, like:<br />Mar 1801 or 14 Dec<br />If you are not sure, or the date is not confirmed, you could type:<br />abt Mar 1801 (abt = about)<br />bef 20 Dec 1950 (bef = before)<br />aft 1949 (aft = after)<br />Make sure that you enter these dates and abbreviations in English, because then the GEDCOM file is exchangeable and the program will translate all dates and abbreviations properly in the desired language.<br />Also the program has to calculate with the dates. If improper dates are entered in the date fields of the GEDCOM file, the program will not be able to calculate properly.<br />";
$pgv_lang["def_pgv_help"]               = "~PhpGedView~<br />PhpGedView (or PGV) is a program designed by <A HREF=\"https://sourceforge.net/users/yalnifj/\" TARGET=\"_blank\">John Finlay</A> to view GEDCOM files on line.<br />As you can see, PGV does not just put static pages on the web, but is dynamic and can be customized in many ways.<br />John started developing the program on his own, but an entire international team of developers and translators has since joined him and is working to improve the program.<br />Apart from just viewing GEDCOM files, PGV also allows adding and editing events on-line now.<br />";
$pgv_lang["def_theme_help"]             = "~#pgv_lang[heading_theme]#~<br />This site can have some different \"looks\", called Themes.<br />The site administrator chooses a Theme for startup.<br />Everybody who enters this site will see the same Look (Theme). When the site admin has set up the site in a way that logged in users can choose their own theme, they can find out for themselves what they like most.<br />If a user has chosen a different Theme, he/she will have that site layout, as soon as he/she is logged in.<br />";

//-- Index-page MyGEDCOM
$pgv_lang["mygedview_portal_help"]      = "~#pgv_lang[upper_mygedview]#~<br />This is your Personal #pgv_lang[mgv]# Page.<br />You may find here easy links to access your personal data, like <b>My Account, My Indi</b> (this is your Individual Page), <b>My Pedigree</b>.<br />Furthermore you can have a block with <b>Messages</b>, a <b>Journal</b> (like a Notepad) and many more.<br /><br />The layout of this page works the same as the Welcome Page.<br />But while the parts of the Welcome Page are selected by the site adminstrator, you select what parts to include on this page.<br /><br />In the Welcome Block on this page you will find the link to customize this page.<br />You can choose from the following blocks:<br /><br />";
$pgv_lang["mygedview_customize_help"]   = "~#pgv_lang[customize_page]#~<br />When you entered here for the first time, you already had some blocks on this page.<br />If you like, you can customize this Portal.<br />Clicking this link will bring you to a form in a pop up window, in which you can add, delete or move around blocks.<br />More explanation is available on that form.<br />";
$pgv_lang["mygedview_message_help"]     = "~#pgv_lang[user_messages_block]#~<br />In this block you will find the messages sent to you by other users or the admin.<br />Of course, you too can send messages to other users or admin.<br />The PhpGedView mail system is designed to help protect your privacy.  You don't have to leave your email address here and others will not be able to see your email address.<br />";
$pgv_lang["mygedview_favorites_help"]   = "~#pgv_lang[user_favorites_block]#~<br />My favorites works like bookmarks.<br />Suppose you have somebody in the family tree whose record you want to check regularly.<br />Just go to the person's individual page, and select the \"Add to My Favorites\" option from the favorites drop-down list. This person is now book marked and added to your list of Favorites.<br />Wherever you are on this site, you can click on a name in the \"My Favorites\" drop down list in the header.<br />This will forward you to the individual page of the person.<br /><br />To save space, the boxes are displayed with limited information. At the right side of the name box you see the magnifying glass to reveal some more information.<br />Clicking the name will forward you to the individual page of the person.<br />Also at the right side you will find a menu that can take you to pages with more information or charts.<br />";
$pgv_lang["mygedview_myjournal_help"]   = "~#pgv_lang[user_news_block]#~<br />You can use this journal to write notes (or reminders) for your own use.<br />Of course, when you make a note, it will still be there, the next time when you visit the site.<br /><br />These notes will not be visible for others.<br />";
$pgv_lang["mygedview_welcome_help"]     = "~#pgv_lang[welcome_block]#~<dt>This Welcome block shows you:</dt><dd>- The current GEDCOM file</dd><dd>- The date and time</dd><dd>- Links to:</dd><dd> - - #pgv_lang[myuserdata]#</dd><dd>- - #pgv_lang[my_pedigree]# (see remark)</dd><dd>- - #pgv_lang[my_indi]# (see remark)</dd><dd>- - #pgv_lang[customize_page]#</dd></dl><b>Remark</b><br />You will see the links to \"My Indi\" and \"My Pedigree\" only if you have a record in the current GEDCOM file.<br />So, it may be that in one GEDCOM file you have a record, and see the links \"My Indi\" and \"My Pedigree\", while in another GEDCOM file you do not have a record and \"My Indi\" and \"My Pedigree\" are not displayed.<br />";

//-- Pedigree-page
$pgv_lang["help_pedigree.php"]          = "~#pgv_lang[index_header]#.~<br /><br />L'arbre d'ascendance d'une personne est la liste de ses ancêtres : son père, sa mère, leurs parents, etc...<br />Les informations concernant chaque personne s'affichent dans des boîtes, et offrent des liens vers d'autres pages.<dl><dt>Boîtes</dt><dd>Avec l'option <a href=\"?help=show_full_help\">#pgv_lang[show_details]#</a>, les informations principales (naissance, mariage, décès) sont affichées.<br />Dans le cas contraire, seul le nom est indiqué.<br />En cliquant sur le nom, vous êtes redirigé vers la page <a href=\"?help=help_individual.php\">#pgv_lang[personal_facts]#</a> de l'individu.<br /></dd><dt>Sous-menu</dt><dd>Avec l'option <a href=\"?help=show_full_help\">#pgv_lang[show_details]#</a>, une première image dans la boîte affiche un sous-menu.<br />Ce sous-menu est similaire au <a href=\"?help=menu_charts_help\">#pgv_lang[menu]# «#pgv_lang[charts]#»</a>, sauf que l'#pgv_lang[root_person]# est remplacé par la personne indiquée dans la boîte.<br />D'autres liens permettent de naviguer vers conjoints et enfants.</dd><dt>Zoom</dt><dd>Une deuxième image offre un zoom donnant davantage de détails sur l'individu choisi.</dd><dt>Flèches</dt><dd>Aux extrêmes gauche et droite du graphique, des flèches facilitent la navigation par génération.</dd></dl>";
$pgv_lang["show_full_help"]             = "~#pgv_lang[show_details]#~<br /><br />Option pour afficher les détails de chaque individu sur le diagramme.<br /><br />Détails masqués, vous pouvez afficher davantage de personnes sur une page.<br />Pour voir les détails, il suffit alors soit de cliquer, soit de passer la souris sur la case. Cela dépend de la configuration choisie par l'administrateur.";
$pgv_lang["talloffset_help"]            = "~#pgv_lang[portrait]# / #pgv_lang[landscape]#~<br /><br />#pgv_lang[PEDIGREE_LAYOUT_help]#<br />Utile avec un écran pivotable, ou pour faire une impression d'écran (print-screen).";
$pgv_lang["rootid_help"]                = "~#pgv_lang[rootid]#~<br /><br />Pour démarrer d'une autre personne, entrez son code, appelé identifiant GEDCOM, ou plus simplement <b>ID</b>.<br />Par exemple <tt>I65</tt>.<br />Si vous ne le connaissez pas, utilisez le lien «#pgv_lang[find_id]#».";
$pgv_lang["PEDIGREE_GENERATIONS_help"]  = "~#pgv_lang[generations]#~<br /><br />#pgv_lang[generations]# à afficher sur cette page.<br />A règler en fonction de la taille de votre écran, et suivant que vous affichez les détails ou non.";

//-- LOGIN-page
$pgv_lang["login_page_help"]            = "~#pgv_lang[login]#~<br /><br />Sur cette page vous pouvez : vous connecter, #pgv_lang[requestaccount]# ou #pgv_lang[requestpassword]#.<br />";
$pgv_lang["username_help"]              = "~#pgv_lang[username]#~<br /><br />Entrer ici votre nom d'utilisateur.<br />Respecter majuscules/minuscules.";
$pgv_lang["password_help"]              = "~#pgv_lang[password]#~<br /><br />Entrer ici votre mot de passe.<br />Respecter majuscules/minuscules.";
$pgv_lang["login_buttons_help"]         = "~#pgv_lang[login]# / #pgv_lang[admin]#~<br /><br />Sur cette page, deux boutons vous sont proposés :<dl><dt>#pgv_lang[login]#</dt><dd>Ce bouton vous ramènera vers la page par laquelle vous êtes venu.</dd><dt>#pgv_lang[admin]#</dt><dd>Si vous avez les droits administrateur, vous pouvez utiliser ce bouton pour accéder directement à la page Administration.</dd></dl>";
$pgv_lang["new_password_help"]          = "~#pgv_lang[requestpassword]#~<br />Si vous avez perdu votre mot de passe, cliquez sur ce lien.<br />Vous serez redirigé vers le formulaire de \"#pgv_lang[lost_pw_reset]#\".";
$pgv_lang["new_user_help"]              = "~#pgv_lang[requestaccount]#~<br /><br />Si vous souhaitez demander un compte d'accès personnel, cliquez sur ce lien.<br />Vous serez redirigé vers le formulaire de demande de compte.";
$pgv_lang["mygedview_login_help"]       = "Pour accéder au portail «Mon GedView», vous devez vous identifier.<br /><br />Avec le portail «Mon GedView» vous pourrez mémoriser vos préférences, conserver un journal, gérer vos messages, voir les autres utilisateurs connectés...<br /><br />Connectez-vous :";
$pgv_lang["new_user_fullname_help"]     = "~#pgv_lang[fullname]#~<br /><br />Entrez ici votre nom complet.<br /><br />C'est ce nom qui s'affichera aux autres utilisateurs connectés.<br /><br />Ce nom est nécessaire pour vérifier votre parenté et vous donner les droits appropriés.";

//-- Descendancy-page
$pgv_lang["help_descendancy.php"]       = "~#pgv_lang[descend_chart]#~<br /><br />L'arbre de descendance d'une personne est la liste de ses enfants, petits-enfants, etc... avec leurs conjoints.<br /><br />Fonctionnement des boutons, sous-menus et liens similaire à l'<a href=\"?help=help_pedigree.php\">#pgv_lang[index_header]#</a>.<br />Pour davantage de lisibilité, chaque branche peut s'ouvrir <img src=\"images/plus.gif\" /> ou se fermer <img src=\"images/minus.gif\" /> d'un simple clic.<br />La <a href=\"?help=box_width_help\">#pgv_lang[box_width]#</a> est également modifiable.<br /><br />En marge est indiqué le numéro de descendant selon le système d'Aboville.<br />Ainsi le 1.2.5 est le cinquième enfant du deuxième enfant de l'individu racine.";
$pgv_lang["desc_rootid_help"]           = "#pgv_lang[rootid_help]#";
$pgv_lang["desc_generations_help"]      = "#pgv_lang[PEDIGREE_GENERATIONS_help]#";

//-- Time line-page
$pgv_lang["help_timeline.php"]          = "~#pgv_lang[timeline_chart]#~<br /><br />Affiche les évènements d'une ou plusieurs personnes sur une même ligne de temps, permettant de les comparer.";
$pgv_lang["add_person_help"]            = "~#pgv_lang[add_another]#~<br /><br />Pour ajouter une personne, entrez son identifiant GEDCOM (exemple: <tt>I65</tt>).<br />Si vous ne le connaissez pas, utilisez le lien «#pgv_lang[find_id]#».";
$pgv_lang["remove_person_help"]         = "~#pgv_lang[remove_person]#~<br /><br />Pour retirer une personne du diagramme.<br />La fiche de cette personne n'est ni modifiée, ni supprimée.";
$pgv_lang["show_age_marker_help"]       = "~#pgv_lang[show_age]#~<br /><br />Option pour activer le marqueur d'âge, affichant l'âge de la personne à une année donnée.<br />Le marqueur se déplace sur la ligne de temps avec la souris.<br />Il existe un marqueur pour chacune des personnes sur le diagramme.";

//-- Relationship-page
$pgv_lang["help_relationship.php"]      = "~#pgv_lang[relationship_chart]#~<br /><br />Recherche du lien de parenté entre deux personnes.<br />Il peut s'agir d'un lien direct (de sang) ou d'un lien indirect (par mariage).";
$pgv_lang["relationship_id_help"]       = "~#pgv_lang[id]# #pgv_lang[person1]# #pgv_lang[person2]#~</b><br /><br />Si, sur la page précédente, vous avez cliqué «#pgv_lang[relationship_to_me]#», les deux champs sont déjà renseignés.<br />Sinon, sélectionnez deux individus en entrant leur ID, ou en cliquant sur «#pgv_lang[find_id]#»";
$pgv_lang["next_path_help"]             = "~#pgv_lang[next_path]#~<br /><br />Bouton pour afficher le prochain lien de parenté, s'il existe.<br />Pour réafficher un lien de parenté précédent, cliquer sur son numéro dans la liste.";
$pgv_lang["follow_spouse_help"]         = "~#pgv_lang[follow_spouse]#~<br /><br />Option pour élargir la recherche aux liens par mariage.<br />Sinon, seuls les liens de sang sont pris en compte.";
$pgv_lang["line_up_generations_help"]   = "~#pgv_lang[line_up_generations]#~<br /><br />Option pour afficher les personnes de même génération sur une ligne horizontale.<br/>Sinon, les individus sont affichés à la suite sur la page, sans tenir compte des générations.";
$pgv_lang["oldest_top_help"]            = "~#pgv_lang[oldest_top]#~<br /><br />Option pour afficher les résultats dans le sens parents-enfants du haut vers le bas.<br/>Par défaut, c'est l'inverse : les individus les plus jeunes sont affichés en premier.<br /><br />Ne fonctionne que si l'option <a href=\"?help=line_up_generations_help\">#pgv_lang[line_up_generations]#</a> est activée.";

//-- Ancestry-page
$pgv_lang["help_ancestry.php"]          = "~#pgv_lang[ancestry_chart]#~<br /><br />Cette page affiche les ancêtres d'une personne, comme l'<a href=\"?help=help_pedigree.php\">#pgv_lang[index_header]#</a>, mais d'une façon plus détaillée, et avec plusieurs choix de <a href=\"?help=chart_style_help\">#pgv_lang[chart_style]#</a>.<br /><br />A chaque ancêtre est attribué un numéro unique, selon le système <i>Sosa-Stradonitz</i>, le plus répandu dans le monde :<br /> - pair pour les hommes (double de celui de son enfant)<br /> - impair pour les femmes (numéro de son mari +1) avec une exception pour le <big>1</big><br /><br />Ainsi le <big>7</big> est la femme du <big>6</big>, la mère du <big>3</big>, et la fille des <big>14</big> et <big>15</big>.";
$pgv_lang["box_width_help"]             = "~#pgv_lang[box_width]#~</b><br /><br />Vous pouvez faire varier la largeur des boîtes entre 50% et 300%.<br />La valeur initiale est 100% : chaque boîte fait environ 270 pixels de large.";
$pgv_lang["chart_style_help"]           = "~#pgv_lang[chart_style]#~<br /><br />Choix entre :<dl><dt>#pgv_lang[ancestry_list]#</dt><dd>L'arbre, présenté verticalement, comporte autant de niveaux que de générations, avec à chaque fois deux branches : celle du père (numéro pair) et celle de la mère (numéro impair).</dd><dt>#pgv_lang[ancestry_booklet]#</dt><dd>Présentation d'une famille par page avec les parents, les grand-parents et la liste de tous les enfants connus. Ce format est idéal pour imprimer le récapitulatif d'une famille et l'offrir à vos proches</dd></dl>";

//-- Fan chart-page
$pgv_lang["help_fanchart.php"]          = "~#pgv_lang[fan_chart]#~<br /><br />Cette page affiche les ancêtres d'une personne, comme l'<a href=\"?help=help_pedigree.php\">#pgv_lang[index_header]#</a>, mais d'une façon plus visuelle : sous la forme d'une roue ou d'un éventail.<br />L'individu racine est au centre, ses parents sur la première couronne, les grand-parents sur la seconde ...<br /><br />Pour chaque personne, figurent son nom et ses dates de naissance et décès.";
$pgv_lang["fan_width_help"]             = "~#pgv_lang[fan_width]#~</b><br /><br />Vous pouvez faire varier la taille de la roue entre 50% et 300%.<br />La valeur initiale est 100% : l'image de la roue fait environ 640 pixels de large.";
$pgv_lang["fan_style_help"]             = "~#pgv_lang[chart_style]#~<br /><br /><dl><dt>1/2</dt><dd>Demi-roue (180°)</dd><dt>3/4</dt><dd>Trois-quarts de roue (270°) ou 'Roue du paon'</dd><dt>4/4</dt><dd>Roue entière (360°)</dd></dl>";

//-- Clippings Cart-page
$pgv_lang["help_clippings.php"]         = "~#pgv_lang[clippings_cart]#~<br />Cette fonction vous permet d'extraire certaines parties de l'arbre sous la forme d'un fichier au format GEDCOM, compatible avec d'autres logiciels de généalogie.<dl><dt>Comment choisir les parties à extraire ?</dt><dd>C'est très simple : sur la page détaillée d'un INDIvidu, d'une FAMille ou d'une SOURce, cliquer sur le bouton <b>#pgv_lang[add_to_cart]#</b></dd><dt>Comment enregistrer le panier ?</dt><dd>Pour récupérer le contenu de votre panier, ouvrir le menu <b>#pgv_lang[clippings_cart]#</b>, puis cliquer sur <b>#pgv_lang[download_now]#</b>.</dd></dl>";
$pgv_lang["clip_download_help"]         = "~#pgv_lang[download_now]#~<br /><br />By clicking this link, you will be forwarded to the next page.<br />If there are more option what to download, they will be displayed on that page.<br />Simply follow the instructions.";
$pgv_lang["empty_cart_help"]            = "~#pgv_lang[empty_cart]#~<br /><br />By clicking this link, your Clipping Cart will be totally emptied.<br /><br />If you don't want to remove all persons, families, etc. from the Clipping Cart, you can remove item by item by clicking the \"Remove\" link in the name boxes. ";


//-- Search-page
$pgv_lang["search_enter_terms_help"]    = "~#pgv_lang[enter_terms]#~<br /><br />Vous pouvez faire une recherche par date, nom, prénom, lieu, etc.<dl><dt>Jokers</dt><dd>Les jokers (comme * ou ?), ne sont pas autorisés, mais le programme en tient compte.<br />Comment ?<br />Supposons que vous avez saisi : \"<b>Mar</b>\"<br />Le résultat donnera :<br />Jean-<b>Mar</b>c Durand<br /><b>Mar</b>cel Lebrin<br />Paul <b>Mar</b>tin<br />une personne née à <b>Mar</b>seille<br />etc..</dd><dt>Dates</dt><dd>En entrant une date, vous obtiendrez la liste de toutes les personnes liées à cette date.<br /><B>1950</B>, par exemple, vous donnera la liste des personnes, nées en 1950, ou mariées, ou décédées, ou....tout autre évènement de 1950.<br /><br />Avec <b>4 Dec</b>, toutes les personnes en rapport avec le 4 décembre de n'importe quelle année.<br />Mais aussi les évènements du 14 et du 24 décembre.<br />Encore une fois, les jokers ne sont pas nécessaires.</dd><dt>Dates exactes</dt><dd>Attention, le programme cherche les dates au format interne GEDCOM.<br />Ainsi, pour faire une recherche concernant le 14 décembre, il faut taper :<b>14 dec</b>.<br />Saisir <b>dec 14</b>, vous afficherait les évènements du 6 <b>dec</b>embre 19<b>14</b></dd></dl>.";

//-- Add Facts
$pgv_lang["add_media_help"]             = "~#pgv_lang[add_media]#~<br /><br />L'ajout de'OBJEts MultiMedia (MM) à votre base GEDCOM la rend très agréable à consulter.<dl><dt>Ce qu'il faut savoir sur les OBJEts MultiMedia.</dt><dd>De nombreux formats existent. PhpGedView en reconnaît la grande majorité</dd><dt>Formats</dt><dd>Les images peuvent s'enregistrer sous plusieurs formats (.jpg .png .bmp .gif ...)<br />Pour un affichage presque identique, la taille du fichier peut varier énormément selon le format choisi</dd><dt>Résolution</dt><dd>La résolution d'une image se mesure en \"dpi\" (dots per inch = points par pouce). Equivalent en photographie au grain du film 25ASA - 200ASA - 800ASA.<br />La qualité augmente avec la résolution, mais la taille du fichier aussi.<br />Pour une image web, 75 dpi est largement suffisant</dd><dt>Nombre de couleurs</dt><dd>L'autre moyen de diminuer la taille d'un fichier, c'est de réduire le nombre de couleurs utilisées.<br />Entre 8 couleurs et 65M de couleurs, le choix est large. 256 est suffisant</dd><dt>Pourquoi est-il important d'avoir des petits fichiers ?</dt><dd>D'abord parce que la place est limitée sur un serveur web, et l'augmenter coûte cher.<br />Ensuite parce que les gros fichiers sont longs à charger, pour vous et pour vos visiteurs.<br />Tout le monde ne dispose pas d'une connexion haut-débit</dd><dt>Comment ajouter un fichier MM ?</dt><dd>Pour toutes les raisons évoquées, seul l'administrateur possède les droits. Contactez-le. Il chargera le fichier sur le serveur.<br />Vous pourrez ensuite rattacher ce fichier à une personne ou un évènement</dd></dl>";
//-- Edit user
$pgv_lang["mail_option3_help"]          = "Avec cette option, vous recevrez uniquement les messages vers votre adresse courriel.<br />Vous ne serez pas joignable par la messagerie interne.<br />";
$pgv_lang["mail_option4_help"]          = "Avec cette option, vous ne recevrez aucun message.<br />";

//-- User Admin
$pgv_lang["useradmin_visibleonline_help"]= "~#pgv_lang[visibleonline]#~<br /><br />Option pour afficher le statut de connexion (en ligne / hors ligne) aux autres utilisateurs. Si la case est cochée, l'utilisateur sera visible. Sinon il restera caché.";
$pgv_lang["useradmin_editaccount_help"] = "~#pgv_lang[editaccount]#~<br /><br />Option pour autoriser la modification de certains paramètres du compte par l'utilisateur.<br /><br />Si la case n'est <b>pas</b> cochée, les modifications seront interdites.<br /><br />Cette fonction permet de créer un compte générique, utilisable par plusieurs personnes, mais en interdisant à chacun de le modifier.";

//-- G E D C O M
$pgv_lang["add_upload_gedcom_help"]     = "~#pgv_lang[add_gedcom]# / #pgv_lang[upload_gedcom]#~<dl><dt>#pgv_lang[upload_gedcom]#</dt><dd>Le chargement d'un fichier sur le serveur peut se faire directement ici, sans programme de type <tt>ftp</tt>.</dd><dt>#pgv_lang[add_gedcom]#</dt><dd>Quand un GEDCOM est déjà présent sur le serveur, il suffit de le reconfigurer.</dd></dl>Les deux procédures se déroulent très simplement en 4 étapes, seule la première diffère.";
$pgv_lang["default_gedcom_help"]        = "~GEDCOM par défaut~<br /><br />Si vous avez plusieurs GEDCOM en ligne, vous pouvez en désigner un comme GEDCOM par défaut pour les visiteurs du site ou les utilisateurs non encore connectés.<br /><br />Les utilisateurs autorisés peuvent modifier cette valeur par défaut en changeant les paramètres de leur compte.";
$pgv_lang["add_gedcom_help"]            = "~#pgv_lang[add_gedcom]#~<br /><br />Cela suppose que le fichier GEDCOM a déjà été chargé sur le serveur, via <tt>ftp</tt> par exemple.<br /><br />Vous serez guidé tout au long de la procédure.";
$pgv_lang["upload_gedcom_help"]         = "~#pgv_lang[upload_gedcom]#~<br /><br />Le chargement d'un fichier sur le serveur peut se faire directement ici, sans programme de type <tt>ftp</tt>.<br /><br />Il suffit de sélectionner un fichier GEDCOM sur votre poste, soit en entrant le chemin complet comme par exemple <tt>C:\\Program Files\\PAF\\famille.ged</tt>, soit en utilisant le sélecteur de fichier sur la page.<br /><br />D'autres textes d'aide seront disponibles pendant le déroulement de la procédure.";
$pgv_lang["macfile_detected_help"]      = "~Fichier au format Macintosh~<br />PhpGedView a détecté que votre fichier GEDCOM provient d'un ordinateur Macintosh. Les marqueurs de fin de ligne sont différents sur Macintosh (\r), sur Unix (\n) ou sur Windows (\r\n). Pour être utilisable par PhpGedView, ces caractères vont être modifiés.<br />";

//-- Language Editor
$pgv_lang["lang_edit_help"]             = "Page de gestion des fichiers de langue.<br />Pour traduire, comparer et exporter des fichiers de langue.<br />Et configurer les langues reconnues par le programme.<br /><br />Liste des options et utilitaires :";
$pgv_lang["language_to_edit_help"]      = "#pgv_lang[edit_lang_utility]# >> <b>#pgv_lang[language_to_edit]#</b><br /><br />Liste déroulante pour le choix de la langue à éditer.";
$pgv_lang["file_to_edit_help"]          = "#pgv_lang[edit_lang_utility]# >> <b>#pgv_lang[file_to_edit]#</b><br /><br />Liste déroulante pour le choix du fichier de langue.<br /><br />Options possibles:<br />lang.xx.php<br />facts.xx.php<br />configure_help.xx.php<br />help_text.xx.php<br />rs_lang.xx.php<br /><br />où xx est le code de la langue.<br />'rs_lang.xx.php' n'est disponible que si le module 'research log' est installé.";
$pgv_lang["hide_translated_help"]       = "#pgv_lang[edit_lang_utility]# >> <b>#pgv_lang[hide_translated]#</b><br /><br />Si cette option est à 'oui' vous verrez uniquement les messages non encore traduits dans votre langue.<br />Après ajout d'une nouvelle traduction, le message concerné n'est plus affiché dans cette liste.";
$pgv_lang["language_to_export_help"]    = "#pgv_lang[export_lang_utility]# >> <b>#pgv_lang[language_to_export]#</b><br /><br />Liste déroulante pour le choix de la langue dont on souhaite <b>exporter</b> les messages.";
$pgv_lang["new_language_help"]          = "#pgv_lang[compare_lang_utility]# >> <b>#pgv_lang[new_language]#</b><br /><br />Liste déroulante pour le choix de la première langue dont on souhaite <b>comparer</b> les messages.<br /><br />Tous les changements sont faits en premier pour la langue <b>English</b>.";
$pgv_lang["old_language_help"]          = "#pgv_lang[compare_lang_utility]# >> <b>#pgv_lang[old_language]#</b><br /><br />Liste déroulante pour le choix de la seconde langue dont on souhaite <b>comparer</b> les messages.<br /><br />Cliquer ensuite sur le bouton pour lancer la comparaison et vous obtiendrez une liste de toutes les différences.<br /><br />Précision:<br /><b>Ajout</b> signifie: <b>présent</b> dans le premier fichier, mais <b>absent</b> du second.<br /><br /><b>Suppression</b> signifie: <b>absent</b> du premier fichier (supprimé), mais (toujours) <b>présent</b> dans le second.";

//-- report engine
$pgv_lang["help_reportengine.php"]      = "~#pgv_lang[reports]#~<br />PhpGedView utilise un squelette XML pour générer automatiquement un rapport au format PDF.<br /><br />Choisir d'abord un type de rapport dans la liste. Cette liste est générée dynamiquement à partir du contenu du répertoire <tt>reports</tt>. Renseigner ensuite les quelques champs comme le code individu ou le code famille.<br /><br />Pour afficher le résultat dans votre navigateur, cliquer sur <b>#pgv_lang[run_report]#</b>. Pour l'enregistrer sur votre poste, cliquer sur <b>#pgv_lang[download_report]#</b>.<br /><br />Vous pouvez créer vous-même un nouveau modèle en vous inspirant de ceux existant. L'ajouter simplement dans le répertoire <i>'reports'</i> pour qu'il apparaisse dans la liste.";

//-- Help Contents
$pgv_lang["help_contents_head_help"]    = "<b>Sommaire de l'aide</b><br /><br />";
$pgv_lang["help_contents_gedcom_info"]  = "Informations du fichier GEDCOM";
$pgv_lang["help_contents_gedcom_places"]= "Lieux du fichier GEDCOM";

//-- Admin Help Contents Items
$pgv_lang["admin_help_contents_head_help"]= "<b>Sommaire<br /><br /><span class=\"error\"><small>Note : l'aide pour les fonctions <u>administrateur</u> est en début de liste.</small></span></b><br /><br />";
$pgv_lang["ah1_help"]                   = "_Utilitaire de mise à jour des versions";
$pgv_lang["ah2_help"]                   = "_Configurer PhpGedView";
$pgv_lang["ah3_help"]                   = "_GEDCOM: Ajouter vs Charger";
$pgv_lang["ah4_help"]                   = "_GEDCOM: Fichier de Configuration";
$pgv_lang["ah5_help"]                   = "_GEDCOM: Fichier par Défaut";
$pgv_lang["ah6_help"]                   = "_GEDCOM: Suppression";
$pgv_lang["ah7_help"]                   = "_GEDCOM: Ajout";
$pgv_lang["ah8_help"]                   = "_GEDCOM: Création";
$pgv_lang["ah9_help"]                   = "_GEDCOM: Réception (download)";
$pgv_lang["ah10_help"]                  = "_GEDCOM: Administration";
$pgv_lang["ah11_help"]                  = "_GEDCOM: Configuration";
$pgv_lang["ah12_help"]                  = "_GEDCOM: Import";
$pgv_lang["ah13_help"]                  = "_GEDCOM: Envoi sur serveur (upload)";
$pgv_lang["ah14_help"]                  = "_GEDCOM: Validation";
$pgv_lang["ah15_help"]                  = "_GEDCOM: Conversion ANSI en UTF-8";
$pgv_lang["ah16_help"]                  = "_GEDCOM: Règles de confidentialité";
$pgv_lang["ah17_help"]                  = "_Gestion des utilisateurs";
$pgv_lang["ah18_help"]                  = "_Administration";
$pgv_lang["ah19_help"]                  = "_GEDCOM: Outils Media";
$pgv_lang["ah20_help"]                  = "_GEDCOM: Conversion ID en RIN";
$pgv_lang["ah21_help"]                  = "_Fichiers de langues";
//           22 is in the help_text_vars.php

?>
